app:
  # dev开发环境 test测试环境 prod线上环境
  mode: dev
  # 服务名称
  name: testApp
  # 端口号
  port: 8001 # 服务端口号
  readTimeout: 1
  writerTimeout: 2
  # 数据权限功能开关
  enableDp: false
  # 后端接口地址
  baseUrl: "http://127.0.0.1"
  isApiMysql: false

zap:
  # 日志等级, trace, debug, info, warn, error, fatal
  level: info
  prefix: '[test-goadmin]'
  format: console # console json
  path: logs
  logFile: ['app', 'login', 'h5']
  encodeLevel: LowercaseColorLevelEncoder
  stacktraceKey: stacktrace
  maxAge: 24
  showLine: false
  logInConsole: false

jwt:
  # token 密钥，生产环境时及的修改
  secret: go-admin
  # token 过期时间 单位：秒
  expiresTime: 604800
  signingKey: "232323"
  issuer: "test"

database:
  mysql:
    driver: mysql
    username: root
    password: root
    host: 127.0.0.1
    port: 3306
    dbname: test-goadmin
    tablePrefix: "test_"
    extra: "parseTime=true&loc=Local"
    maxIdConnect: 100
    maxOpenConnect: 100
    charset: "utf8mb4"

email:
  # 是否不启用
  disabled: true
  # 默认发件人
  from: 1147422686@qq.com
  # 服务器地址
  host: smtp.qq.com
  # 服务器端口 465/587
  port: 587
  # 服务器账户
  username: test
  # 服务器密码
  password: D7Pt2goBw7PcxANJUe5IGV

dingDing:
  env: dev,test
  url: https://oapi.dingtalk.com/robot/send
  secret: SECcd67b268b114189d745ca2a324b8374104c1e18d765d9b99e0bf183cb309492e
  accessToken: 74cf3455dfa3c7f2941a79888f2700c6a91b7f6a69b056db0af2e6168a39a5d0

session:
  secret: "secret"

upload:
  # 上传文件大小
  maxMemory: 10
  # 默认保存路径
  path: "resource/upload/"
